<?php

namespace Database\Seeders;

use Data\Enums\Tables;
use Data\Processors\DataZipCodeRowProcessor;
use Data\Readers\CsvFileReader;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $dataSourceFile = env('APP_DATA_SOURCE_FILE');
        $fileReader = new CsvFileReader($dataSourceFile);
        $dataProcessor = new DataZipCodeRowProcessor();
        foreach ($fileReader->getRows() as $rows) {
            $rowsToInsert = [
                Tables::federal_entities->name => [],
                Tables::municipalities->name => [],
                Tables::zip_codes->name => [],
                Tables::settlement_types->name => [],
                Tables::settlements->name => [],
            ];
            foreach ($rows as $row) {
                $preProcessedRow = $dataProcessor->preProcessRow($row);
                $dataProcessor->processRow($preProcessedRow, $rowsToInsert);
            }
            $this->insertModels($rowsToInsert);
        }
    }

    /**
     * Insert models generated by the data processor into its
     * corresponding table.
     *
     * @param  array  $modelsByTable Array of models classified by table.
     * @return void
     */
    protected function insertModels(array $modelsByTable): void
    {
        if (count($modelsByTable[Tables::federal_entities->name]) > 0) {
            $table = Tables::federal_entities->name;
            DB::table($table)->insert($modelsByTable[$table]);
        }
        if (count($modelsByTable[Tables::municipalities->name]) > 0) {
            $table = Tables::municipalities->name;
            DB::table($table)->insert($modelsByTable[$table]);
        }
        if (count($modelsByTable[Tables::zip_codes->name]) > 0) {
            $table = Tables::zip_codes->name;
            DB::table($table)->insert($modelsByTable[$table]);
        }
        if (count($modelsByTable[Tables::settlement_types->name]) > 0) {
            $table = Tables::settlement_types->name;
            DB::table($table)->insert($modelsByTable[$table]);
        }
        if (count($modelsByTable[Tables::settlements->name]) > 0) {
            $table = Tables::settlements->name;
            DB::table($table)->insert($modelsByTable[$table]);
        }
    }
}
